---
- name: Shutdown and delete a VM in Proxmox
  hosts: proxmox
  vars_prompt:
    - name: "vm_id"
      prompt: "Enter the VM ID to delete"
      private: no

  tasks:
    - name: Shutdown the VM
      ansible.builtin.command:
        argv:
          - qm
          - stop
          - "{{ vm_id }}"
      ignore_errors: yes

    - name: Remove the VM
      ansible.builtin.command:
        argv:
          - qm
          - destroy
          - "{{ vm_id }}"
          - --purge
      ignore_errors: yes
