test_webserver:
  hosts:
    test-webserver-au-adelaide:
      ansible_host: au-adelaide.tombarone.net
      ansible_user: cloudinit
      ansible_port: 9050
      ansible_python_interpreter: /usr/bin/python3
